# Generated by Django 5.2.3 on 2025-07-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerdetail',
            old_name='order_type',
            new_name='offer_type',
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='business_user',
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='customer_user',
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='status',
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='offers/'),
        ),
    ]
