# Generated by Django 5.2.3 on 2025-07-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_remove_offerdetail_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='creator_id',
            field=models.IntegerField(default=0),
        ),
    ]
